apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster15
  namespace: guest-book
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
