kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scrambled-controller-authorization
rules:
  - apiGroups:
      - "batch.github.com.golanshabi"
    resources:
      - scrambleds
      - scrambleds/status
    verbs:
      - get
      - list
      - watch
      - update

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scrambled-controller-authorization-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scrambled-controller-authorization
subjects:
  - kind: ServiceAccount
    name: default
    namespace: scramble-app