apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster5
  namespace: deep-model
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: cluster5