apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: i4q-demo
  namespace: deep-model
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - i4q-demo
