apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: i4q-demo-subs
  namespace: deep-model
  labels:
    app: i4q-demo
  annotations:
    apps.open-cluster-management.io/git-path: DeepLearningModel/deployment
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: application-sample/demo-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cluster5
