apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster16
  namespace: book-info
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: cluster19
