apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster15
  namespace: bookinfo
spec:
  clusterConditions:
    - type: "ManagedClusterConditionAvailable"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: cluster15
